<?php
/**
 * @author 18th DigiTech Team
 * @copyright Copyright (c) 2022 18th DigiTech (https://www.18thdigitech.com)
 * @package Eighteentech_Buildbox
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */

$isBoxFound = 0;

?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>

            <?php foreach ($block->getItems() as $_item):
                if ($_item->getBoxId() != '1') {?>
                    <?= $block->getItemHtml($_item) ?>
            <?php } else {
                    $isBoxFound++;
            }
             endforeach ?>
        </table>

        <?php if ($isBoxFound > 0): ?>
            <table id="shopping-box-table"
                class="box">                
                <?php foreach ($block->getItems() as $_items):
                    if ($_items->getBoxId() == '1') {?>
                       <tr>
                           <td>
                                <h2 class="item-inbox"><?= $block->escapeHtml(__('Items In Box')) ?></h2>
                               <div class="BoxName"> 
                                   <h3> 
                                       <span id="box-name">
                                           <?= /* @noEscape */ $_items->getBoxName()?>
                                           <input type="hidden" name="box-name" 
                                           value="<?= /* @noEscape */ $_items->getBoxName()?>"/>
                                        </span>
                                        <span id="name-pop-show" class="editName">
                                            Edit
                                            <input type="hidden" name="edit-box-name-proid" class="edit-box-name-proid"
                                             value="<?= /* @noEscape */ $_items->getProductId()?>"
                                             prodItemId="<?= /* @noEscape */ $_items->getItemId()?>"
                                             boxTitle="<?= /* @noEscape */ $_items->getBoxName()?>"/>
                                        </span>
                                       
                                    </h3>
                                </div>
                            </td>
                        </tr>                  
                        <tr>
                            <td><?= /* @noEscape */ $block->getItemHtml($_items);?></td>
                        </tr>
                            <?php
                    }
                    endforeach
                ?>
            </table>
        <?php endif ?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom">
                 <?= /* @noEscape */ $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= /* @noEscape */ $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= /* @noEscape */ $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @noEscape */
                $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= /* @noEscape */
                    $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= /* @noEscape */ $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= /* @noEscape */
                $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @noEscape */ $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" 
        data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
