<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @category Eighteentech
 * @package  Eighteentech_SplitOrder
 *
 */
 // @codingStandardsIgnoreFile
?>
<?php
//$blockObj= $block->getLayout()->createBlock(\Eighteentech\SplitOrder\Block\CustomerGroups::class);
//$groups = $blockObj->getCustomerGroup();
?>
    
<div class="field choice customer_type">
	<input type="checkbox" name="customer_type" title="I want to register as" value="1" id="customer_type" class="checkbox">
	<label for="customer_type" class="label">
		<span>I want to register as a Company</span>
	</label>
</div>

